baseURL: "https://boii.xyz/"
title: Mr.Boii
paginate: 10
theme: 
  - PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
# enableGitInfo: true

buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true


outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary


# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
markup:
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    noClasses: false
    style: dracula
    lineNumbersInTable: true
    # noHl: false

  goldmark:
    renderer:
      unsafe: true
